###
GET http://localhost:9091/tags

<> 2024-12-14T024345.200.json

###
GET http://localhost:9091/tags?limit=5

<> 2024-12-14T025430.200.json

###
GET http://localhost:9091/tags/specific?tagName=spring

<> 2024-12-14T030839.200.json

###
GET http://localhost:9091/errorStats?limit=10

<> 2024-12-14T032336.200.json

###
GET http://localhost:9091/errorStats/specific?errorType=NullPointerException

<> 2024-12-14T032052.200.json